---
apiVersion: v1
data: {}
kind: ConfigMap
metadata:
  name: commons-operator-configmap
  labels:
    app.kubernetes.io/name: commons-operator
    app.kubernetes.io/instance: commons-operator
    app.kubernetes.io/version: "0.1.0-nightly"
