---
# Source: commons-operator/templates/configmap.yaml
apiVersion: v1
data:
  properties.yaml: |
    version: 0.1.0
    spec:
      units: []
    properties: []
kind: ConfigMap
metadata:
  name: commons-operator-configmap
  labels:
    helm.sh/chart: commons-operator-0.1.0-nightly
    app.kubernetes.io/name: commons-operator
    app.kubernetes.io/instance: commons-operator
    app.kubernetes.io/version: "0.1.0-nightly"
    app.kubernetes.io/managed-by: Helm
