---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: commons-operator-deployment
  labels:
    app.kubernetes.io/name: commons-operator
    app.kubernetes.io/instance: commons-operator
    app.kubernetes.io/version: "0.2.1"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: commons-operator
      app.kubernetes.io/instance: commons-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: commons-operator
        app.kubernetes.io/instance: commons-operator
    spec:
      serviceAccountName: commons-operator-serviceaccount
      securityContext: {}
      containers:
        - name: commons-operator
          securityContext: {}
          image: "docker.stackable.tech/stackable/commons-operator:0.2.1"
          imagePullPolicy: IfNotPresent
          resources: {}
          volumeMounts:
            - mountPath: /etc/stackable/commons-operator/config-spec
              name: config-spec
      volumes:
        - name: config-spec
          configMap:
            name: commons-operator-configmap
