---
# Source: commons-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: commons-operator-deployment
  labels:
    helm.sh/chart: commons-operator-0.1.0-nightly
    app.kubernetes.io/name: commons-operator
    app.kubernetes.io/instance: commons-operator
    app.kubernetes.io/version: "0.1.0-nightly"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: commons-operator
      app.kubernetes.io/instance: commons-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: commons-operator
        app.kubernetes.io/instance: commons-operator
    spec:
      serviceAccountName: commons-operator-serviceaccount
      securityContext:
        {}
      containers:
        - name: commons-operator
          securityContext:
            {}
          image: "docker.stackable.tech/stackable/commons-operator:0.1.0-nightly"
          imagePullPolicy: IfNotPresent
          resources:
            {}
          volumeMounts:
            - mountPath: /etc/stackable/commons-operator/config-spec
              name: config-spec
      volumes:
        - name: config-spec
          configMap:
            name: commons-operator-configmap
