[package]
name = "stackable-commons-operator"
authors = ["Stackable GmbH <info@stackable.de>"]
description = "Stackable Operator for commons"
license = "OSL-3.0"
version = "0.5.0-nightly"
edition = "2021"
repository = "https://github.com/stackabletech/commons-operator"
publish = false

[dependencies]
anyhow = "1.0"
axum = "0.5.17"
base64 = "0.13.1"
clap = "3.2"
futures = { version = "0.3", features = ["compat"] }
hyper = "0.14.23"
openssl = "0.10.42"
pin-project = "1.0.12"
rustls-pemfile = "1.0.1"
serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
snafu = "0.7"
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag = "0.21.1" }
strum = { version = "0.24", features = ["derive"] }
time = { version = "0.3.17", features = ["formatting"] }
tokio = { version = "1.21", features = ["macros", "rt-multi-thread"] }
tokio-rustls = "0.23.4"
tracing = "0.1"

[build-dependencies]
built = { version =  "0.5", features = ["chrono", "git2"] }
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag = "0.21.1" }

[features]

