---
apiVersion: v2
name: commons-operator
version: "24.11.1"
appVersion: "24.11.1"
description: The Stackable Operator for Stackable Commons
home: https://github.com/stackabletech/commons-operator
maintainers:
  - name: Stackable
    url: https://www.stackable.tech
