---
apiVersion: v2
name: commons-operator
version: 0.1.0-nightly
appVersion: "0.1.0-nightly"
description: The Stackable Operator for commons
home: https://github.com/stackabletech/commons-operator
maintainers:
  - name: Stackable
    url: https://www.stackable.tech
