---
apiVersion: v2
name: commons-operator
version: "25.11.0-rc1"
appVersion: "25.11.0-rc1"
description: The Stackable Operator for Stackable Commons
home: https://github.com/stackabletech/commons-operator
maintainers:
  - name: Stackable
    url: https://www.stackable.tech
